/*
 Neuron JavaScript Framework & Library
 author i@kael.me
 Neuron core:loader v5.0.1(active mode)
 author i@kael.me 
*/
(function(c,i,f){i=c[i]=c&&c[i]||{};i.__HOST=c=i.__HOST||c;for(var c=i,k=function(a,d){return e[g.call(a)]||!d&&a&&"object"||f},g=Object.prototype.toString,a=i,b="Boolean Number String Function Array Date RegExp Object".split(" "),d=b.length,e={},m,h,j;d--;)m=b[d],h=m.toLowerCase(),e["[object "+m+"]"]=h,a["is"+m]="Object"===m?j=function(a){return function(e){return!!e&&k(e)===a}}(h):function(a){return function(e){return k(e)===a}}(h);a.isPlainObject=function(a){return!!a&&"[object Object]"===g.call(a)&&
"isPrototypeOf"in a};a.isWindow=function(a){return j(a)&&"setInterval"in a};c._type=k;i.__={};i._env={};i.log=function(){};i._debugOn=function(){i._env.debug=!0}})("undefined"!==typeof exports?exports:this,"DP");
(function(){function c(a,b){for(var d in b)a[d]||(a[d]=b[d])}c(Array.prototype,{indexOf:function(a,b){var d=this.length>>>0,b=Number(b)||0,b=Math[0>b?"ceil":"floor"](b);for(0>b&&(b=Math.max(b+d,0));b<d;b++)if(b in this&&this[b]===a)return b;return-1},lastIndexOf:function(a,b){var d=this.length>>>0,b=Number(b)||d-1,b=Math[0>b?"ceil":"floor"](b);0>b&&(b+=d);for(b=Math.min(b,d-1);0<=b;b--)if(b in this&&this[b]===a)return b;return-1},filter:function(a,b){for(var d=[],e=0,m=this.length;e<m;e++)e in this&&
a.call(b,this[e],e,this)&&d.push(this[e]);return d},forEach:function(a,b){for(var d=0,e=this.length;d<e;d++)d in this&&a.call(b,this[d],d,this)},every:function(a,b){for(var d=0,e=this.length;d<e;d++)if(d in this&&!a.call(b,this[d],d,this))return!1;return!0},map:function(a,b){for(var d=[],e=0,m=this.length;e<m;e++)e in this&&(d[e]=a.call(b,this[e],e,this));return d},some:function(a,b){for(var d=0,e=this.length;d<e;d++)if(d in this&&a.call(b,this[d],d,this))return!0;return!1},reduce:function(a){if("function"!==
typeof a)throw new TypeError(a+" is not an function");var b=this.length>>>0,d=0,e;if(1<arguments.length)e=arguments[1];else{do{if(d in this){e=this[d++];break}if(++d>=b)throw new TypeError("reduce of empty array with on initial value");}while(1)}for(;d<b;d++)d in this&&(e=a.call(null,e,this[d],d,this));return e},reduceRight:function(a){if("function"!==typeof a)throw new TypeError(a+" is not an function");var b=(this.length>>>0)-1,d;if(1<arguments.length)d=arguments[1];else{do{if(b in this){d=this[b--];
break}if(0>--b)throw new TypeError("reduce of empty array with on initial value");}while(1)}for(;0<=b;b--)b in this&&(d=a.call(null,d,this[b],b,this));return d}});var i=Object.prototype.hasOwnProperty,f=!{toString:""}.propertyIsEnumerable("toString"),k="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),g=k.length;c(Object,{create:function(a){function b(){}if(1<arguments.length)throw Error("Object.create only accepts 1 param.");b.prototype=a;
return new b},keys:function(a){if(a!==Object(a))throw new TypeError(a+" is not an object");var b=[],d;for(d in a)i.call(a,d)&&b.push(d);if(f)for(d=0;d<g;d++)i.call(a,k[d])&&b.push(k[d]);return b}});c(String.prototype,{trimLeft:function(){return this.replace(/^\s+/,"")},trimRight:function(){return this.replace(/\s+$/,"")},trim:function(){return this.trimLeft().trimRight()}})})();
(function(c,i){function f(a,e){return function(){return a.apply(e,arguments)}}function k(d,e,m,h,j){var l,q,f,n;h||(h={});j||(j=1);switch(c._type(d)){case "array":n=[],l=!0;case "object":if(!c.isPlainObject(d)&&!l)return d;l=a;n||(n={});if(d[l])return h[d[l]];q=b++;d[l]=q;m[q]=d;h[q]=n;for(f in d)if(q=d[f],f!==l&&(!e||e.call(d,q,f,j)))n[f]=k(q,e,m,h,j+1);return n;case "date":return new Date(d);case "regexp":return RegExp(d);default:return d}}var g=Array.prototype.join,a=">_>~cloned",b=1;c.mix=function(a,
e,b,h){if(!e||!a)return a;var c=0,l,f,b=b||b===i;if(h&&(f=h.length))for(;c<f;c++){if(l=h[c],l in e&&(b||!(l in a)))a[l]=e[l]}else for(l in e)if(b||!(l in a))a[l]=e[l];return a};c.guid=function(){return b++};c.each=function(a,e,b){if(c.isFunction(e))if(b=b||a,c.isObject(a))for(var h=Object.keys(a),j=0,l=h.length,f;j<l;j++)f=h[j],a.hasOwnProperty(f)&&e.call(b,a[f],f);else c.isArray(a)&&a.forEach(e,b)};c.clone=function(b,e){var m={},h=a,j=k(b,e,m);c.each(m,function(a){try{delete a[h]}catch(e){c.log("del clone m err",
e),a[h]=void 0}});m=null;return j};c.bind=function(a,e){return c.isFunction(a)?f(a,e):e[a]=f(e[a],e)};c.delay=function(a,e,b){var h={start:function(){h.cancel();return h.id=b?setInterval(a,e):setTimeout(a,e)},cancel:function(){var a=h.id;h.id=b?clearInterval(a):clearTimeout(a);return h}};return h};c.makeArray=function(a,e,b){e||(e=[]);if(c.isArray(a))e=e.length?e.concat(a):a;else if(null!=a)if(!b&&(null==a.length||!c.isObject(a)||a.nodeType||"setInterval"in a))e.push(a);else for(var b=e,h=a.length,
j=b.length;h--;)b[j+h]=a[h];return e};c.sub=function(a,e){return(""+a).replace(/\\?\{([^{}]+)\}/g,function(a,b){return"\\"===a.charAt(0)?a.slice(1):null!=e[b]?e[b]:""})};c.toQueryString=function(a,e){var b;if(c.isObject(a)){b=c.clone(a,function(a,b,e){return 3>e});var h,j,l=[],f=encodeURIComponent;for(h in b)j=b[h],c.isObject(j)||(c.isArray(j)?j.forEach(function(a){l.push(h+"="+f(a))}):l.push(h+"="+f(j)));b=l.join(e||"&")}else b=a;return b};c._overloadSetter=function(a,b){return function(m,h){var j=
this,f=j;if(c.isObject(m))c.each(m,function(b,e){a.call(j,e,b)});else if(b||c.isString(m))f=a.apply(j,arguments);return f}};c._onceBefore=function(a,b,c){var h=c[b],j=c[a];c[a]=function(){var b;h.call(this);b=j.apply(this,arguments);this[a]=j;return b}};c._memoize=function(a){var b={};return function(){var c=g.call(arguments,"~^_^~");return c in b?b[c]:b[c]=a.apply(this,arguments)}}})(DP);
(function(c){function i(b){var d=f,e,b=b.match(a);e=b[3];return{href:b[0],protocol:b[1],host:b[2]+(e?":"+e:g),hostname:b[2],port:d(e),pathname:d(b[4]),search:d(b[5]),hash:d(b[6])}}function f(a){return a||g}var k=c.__HOST.document,g="",a=/^([\w\+\.\-]+:)?\/\/([^\/?#:]+)(?::(\d+))?(\/[^?#]*)?(\?[^#]*)?(#.*)?$/;c.getLocation=function(a){if(a)a=i(a);else{var d;try{d=k.location}catch(e){a=k.createElement("a"),a.href=g,a=a.href,d=i(a)}a=d}return a}})(DP);
(function(c){function i(a){var b,h=c._type(a);"function"===h?b=a.prototype:"object"===h?b=a:"string"===h&&(b=i(d[a.toLowerCase()]));return b}function f(a,b,d){"string"===typeof b&&(b=b.trim().split(/\s+/));c.makeArray(b).forEach(function(a){(a=i(a))&&c.mix(this,c.clone(a),d)},a)}function k(a){var b,d;for(d in a){b=a[d];if(c.isPlainObject(b)){var j=function(){};j.prototype=b;b=k(new j)}else b=c.clone(b);a[d]=b}return a}function g(e,d){if(!c.isObject(d))if(c.isObject(e))d=e,e=d.Extends;else return c.isFunction(e)?
e:function(){};delete d.Extends;var h=e,j=d,l=function(){var a=i;k(this);if(a)return a.apply(this,arguments)},g,i=j[a]||h,n=j.Implements;delete j[a];delete j.Implements;h?(g=function(){},g.prototype=h.prototype,g=new g,n&&f(g,n,!0),g[b]=h,c.mix(g,j)):(g=j,n&&f(g,n,!1));l.prototype=g;return g.constructor=l}var a="initialize",b="superclass",d={};c.Class=g;g.EXTS=d;g.setAttrs=function(a,d){for(var h,j=a;(j=j.prototype[b])&&!(h=j.ATTRS););a.ATTRS=c.mix(d||{},c.clone(h))};g.implement=f})(DP);
(function(c){function i(c,a,b){a=a[b];return"string"===typeof a?c[a]:a}var f=c.isPlainObject,k={};["addAttr","get","set"].forEach(function(g){k[g]=function(){var a=this.constructor,b;do if(b=a.ATTRS)break;while(a=a.prototype.superclass);var d=b?c.clone(b):{};this.set=c._overloadSetter(function(a,b,h){if(a=d[a]){var j=!0,l,g;a.readOnly?j=!1:(j=i(this,a,"validator"),j=!j||j.call(this,b));j&&a.writeOnce&&(delete a.writeOnce,a.readOnly=!0);j&&((l=i(this,a,"setter"))?a.value=l.call(this,b):!h&&f(b)&&f(g=
a.value)?c.mix(g,b):a.value=b);b=j}else b=!1;return b});this.get=function(a){var b=d[a];b?(a=i(this,b,"getter"),b=b.value,a=a?a.call(this,b):b):a=void 0;return a};this.addAttr=function(a,b){d[a]||(d[a]=c.isObject(b)?c.clone(b):{})};return this[g].apply(this,arguments)}});c.Class.EXTS.attrs=k;k=null})(DP);
(function(c){function i(c,f){var a;a=c.__ev||(c.__ev={});return a[f]||(a[f]=[])}function f(f,g,a,b){var g=i(f,g),d=0,e=g.lenth;if(b)c.isFunction(a)&&g.push(a);else if(c.isFunction(a))for(;d<e;d++)g[d]===a&&g.splice(d,1);else a||(g.length=0);return f}c.Class.EXTS.events={on:c._overloadSetter(function(c,g){return f(this,c,g,!0)}),off:function(c,g){return f(this,c,g)},fire:function(f,g){var a=this,g=c.makeArray(g);i(a,f).forEach(function(b){b.apply(a,g)});return a}}})(DP);
(function(){var c={isNativeCode:function(a){return/\{\s*\[native code\]\s*\}/.test(""+a)},isXML:function(a){return!!a.xmlVersion||!!a.xml||"[object XMLDocument]"===Object.prototype.toString.call(a)||9===a.nodeType&&"HTML"!==a.documentElement.nodeName},setDocument:function(a){if(9!==a.nodeType)if(a.ownerDocument)a=a.ownerDocument;else if(a.navigator)a=a.document;else return;if(this.document!==a){this.document=a;var b=this.root=a.documentElement;this.brokenStarGEBTN=this.starSelectsClosedQSA=this.idGetsName=
this.brokenMixedCaseQSA=this.brokenGEBCN=!1;var d,e,c,h;if(!(this.isXMLDocument=this.isXML(a))){var j=a.createElement("div");this.root.appendChild(j);var f;j.appendChild(a.createComment(""));e=0<j.getElementsByTagName("*").length;try{j.innerHTML="foo</foo>",d=(f=j.getElementsByTagName("*"))&&f.length&&"/"==f[0].nodeName.charAt(0)}catch(g){}this.brokenStarGEBTN=e||d;if(j.querySelectorAll)try{j.innerHTML="foo</foo>",this.starSelectsClosedQSA=(f=j.querySelectorAll("*"))&&f.length&&"/"==f[0].nodeName.charAt(0)}catch(i){}try{j.innerHTML=
"<a name=slick_id_gets_name></a><b id=slick_id_gets_name></b>",this.idGetsName=j.ownerDocument.getElementById("slick_id_gets_name")===j.firstChild}catch(n){}try{j.innerHTML='<a class="MiXedCaSe"></a>',this.brokenMixedCaseQSA=!j.querySelectorAll(".MiXedCaSe").length}catch(u){}try{j.innerHTML='<a class="f"></a><a class="b"></a>',j.getElementsByClassName("b").length,j.firstChild.className="b",h=2!=j.getElementsByClassName("b").length}catch(k){}try{j.innerHTML='<a class="a"></a><a class="f b a"></a>',
c=2!=j.getElementsByClassName("a").length}catch(z){}this.brokenGEBCN=h||c;this.root.removeChild(j);j=null}this.hasAttribute=b&&this.isNativeCode(b.hasAttribute)?function(a,b){return a.hasAttribute(b)}:function(a,b){a=a.getAttributeNode(b);return!(!a||!a.specified&&!a.nodeValue)};this.contains=b&&this.isNativeCode(b.contains)?function(a,b){return a.contains(b)}:b&&b.compareDocumentPosition?function(a,b){return a===b||!!(a.compareDocumentPosition(b)&16)}:function(a,b){if(b){do if(b===a)return!0;while(b=
b.parentNode)}return!1};this.documentSorter=b.compareDocumentPosition?function(a,b){return!a.compareDocumentPosition||!b.compareDocumentPosition?0:a.compareDocumentPosition(b)&4?-1:a===b?0:1}:"sourceIndex"in b?function(a,b){return!a.sourceIndex||!b.sourceIndex?0:a.sourceIndex-b.sourceIndex}:a.createRange?function(a,b){if(!a.ownerDocument||!b.ownerDocument)return 0;var e=a.ownerDocument.createRange(),d=b.ownerDocument.createRange();e.setStart(a,0);e.setEnd(a,0);d.setStart(b,0);d.setEnd(b,0);return e.compareBoundaryPoints(Range.START_TO_END,
d)}:null;this.getUID=this.isXMLDocument?this.getUIDXML:this.getUIDHTML}},search:function(a,b,d,e){var c=this.found=e?null:d||[];null==b&&(b=a,a=document);if(!a)return c;if(a.navigator)a=a.document;else if(!a.nodeType)return c;var h,j=this.uniques={};this.document!==(a.ownerDocument||a)&&this.setDocument(a);if("string"==typeof b){for(h=this.overrides.length;h--;){var f=this.overrides[h];if(f.regexp.test(b)&&(f=f.method.call(a,b,c,e),!1!==f))return!0===f?c:f}b=this.Slick.parse(b);if(!b.length)return c}else{if(null==
b)return c;if(!b.Slick){if(this.contains(a.documentElement||a,b))c?c.push(b):c=b;return c}}this.posNTH={};this.posNTHLast={};this.posNTHType={};this.posNTHTypeLast={};d=!(!d||!d.length);this.push=!d&&(e||1==b.length&&1==b.expressions[0].length)?this.pushArray:this.pushUID;null==c&&(c=[]);if(d)for(h=c.length;h--;)this.uniques[this.getUID(c[h])]=!0;var g,i,n,u,k,z,o,r,t,w,p,x=b.expressions;h=0;a:for(;p=x[h];h++)for(f=0;t=p[f];f++){n="combinator:"+t.combinator;if(!this[n])continue a;u=this.isXMLDocument?
t.tag:t.tag.toUpperCase();k=t.id;z=t.classList;o=t.classes;r=t.attributes;t=t.pseudos;g=f===p.length-1;this.bitUniques={};g?(this.uniques=j,this.found=c):(this.uniques={},this.found=[]);if(0===f){if(this[n](a,u,k,o,r,t,z),e&&g&&c.length)break a}else if(e&&g){g=0;for(i=w.length;g<i;g++)if(this[n](w[g],u,k,o,r,t,z),c.length)break a}else{g=0;for(i=w.length;g<i;g++)this[n](w[g],u,k,o,r,t,z)}w=this.found}(d||1<b.expressions.length)&&this.sort(c);return e?c[0]||null:c},uidx:1,uidk:"slick:uniqueid",getUIDXML:function(a){var b=
a.getAttribute(this.uidk);b||(b=this.uidx++,a.setAttribute(this.uidk,b));return b},getUIDHTML:function(a){return a.uniqueNumber||(a.uniqueNumber=this.uidx++)},sort:function(a){if(!this.documentSorter)return a;a.sort(this.documentSorter);return a},cacheNTH:{},matchNTH:/^([+-]?\d*)?([a-z]+)?([+-]\d+)?$/,parseNTHArgument:function(a){var b=a.match(this.matchNTH);if(!b)return!1;var d=b[2]||!1,e=b[1]||1;"-"==e&&(e=-1);b=+b[3]||0;b="n"==d?{a:e,b:b}:"odd"==d?{a:2,b:1}:"even"==d?{a:2,b:0}:{a:0,b:e};return this.cacheNTH[a]=
b},createNTHPseudo:function(a,b,d,e){return function(c,h){var j=this.getUID(c);if(!this[d][j]){var f=c.parentNode;if(!f)return!1;var f=f[a],g=1;if(e){var i=c.nodeName;do f.nodeName===i&&(this[d][this.getUID(f)]=g++);while(f=f[b])}else{do 1===f.nodeType&&(this[d][this.getUID(f)]=g++);while(f=f[b])}}h=h||"n";g=this.cacheNTH[h]||this.parseNTHArgument(h);if(!g)return!1;f=g.a;g=g.b;j=this[d][j];if(0==f)return g==j;if(0<f){if(j<g)return!1}else if(g<j)return!1;return 0==(j-g)%f}},pushArray:function(a,b,
d,e,c,h){this.matchSelector(a,b,d,e,c,h)&&this.found.push(a)},pushUID:function(a,b,d,e,c,h){var f=this.getUID(a);!this.uniques[f]&&this.matchSelector(a,b,d,e,c,h)&&(this.uniques[f]=!0,this.found.push(a))},matchNode:function(a,b){var d=this.Slick.parse(b);if(!d)return!0;if(1==d.length&&1==d.expressions[0].length)return d=d.expressions[0][0],this.matchSelector(a,this.isXMLDocument?d.tag:d.tag.toUpperCase(),d.id,d.classes,d.attributes,d.pseudos);for(var d=this.search(this.document,d),e=0,c;c=d[e++];)if(c===
a)return!0;return!1},matchPseudo:function(a,b,d){var e="pseudo:"+b;if(this[e])return this[e](a,d);a=this.getAttribute(a,b);return d?d==a:!!a},matchSelector:function(a,b,d,e,c,h){if(b)if("*"==b){if("@">a.nodeName)return!1}else if(a.nodeName!=b)return!1;if(d&&a.getAttribute("id")!=d)return!1;if(e)for(b=e.length;b--;)if(d="className"in a?a.className:a.getAttribute("class"),!d||!e[b].regexp.test(d))return!1;if(c)for(b=c.length;b--;)if(e=c[b],e.operator?!e.test(this.getAttribute(a,e.key)):!this.hasAttribute(a,
e.key))return!1;if(h)for(b=h.length;b--;)if(e=h[b],!this.matchPseudo(a,e.key,e.value))return!1;return!0}},i={" ":function(a,b,d,e,c,h,f){var g;if(!this.isXMLDocument){if(d){g=this.document.getElementById(d);if(!g&&a.all||this.idGetsName&&g&&g.getAttributeNode("id").nodeValue!=d){f=a.all[d];if(!f)return;f[0]||(f=[f]);for(a=0;g=f[a++];)if(g.getAttributeNode("id").nodeValue==d){this.push(g,b,null,e,c,h);break}return}if(g){if(this.document!==a&&!this.contains(a,g))return;this.push(g,b,null,e,c,h);return}if(this.contains(this.document.documentElement,
a))return}if(e&&a.getElementsByClassName&&!this.brokenGEBCN&&(f=a.getElementsByClassName(f.join(" ")))&&f.length){for(a=0;g=f[a++];)this.push(g,b,d,null,c,h);return}}if((f=a.getElementsByTagName(b))&&f.length){this.brokenStarGEBTN||(b=null);for(a=0;g=f[a++];)this.push(g,b,d,e,c,h)}},">":function(a,b,c,e,f,h){if(a=a.firstChild){do 1===a.nodeType&&this.push(a,b,c,e,f,h);while(a=a.nextSibling)}},"+":function(a,b,c,e,f,h){for(;a=a.nextSibling;)if(1===a.nodeType){this.push(a,b,c,e,f,h);break}},"^":function(a,
b,c,e,f,h){if(a=a.firstChild)if(1===a.nodeType)this.push(a,b,c,e,f,h);else this["combinator:+"](a,b,c,e,f,h)},"~":function(a,b,c,e,f,h){for(;a=a.nextSibling;)if(1===a.nodeType){var g=this.getUID(a);if(this.bitUniques[g])break;this.bitUniques[g]=!0;this.push(a,b,c,e,f,h)}},"++":function(a,b,c,e,f,h){this["combinator:+"](a,b,c,e,f,h);this["combinator:!+"](a,b,c,e,f,h)},"~~":function(a,b,c,e,f,h){this["combinator:~"](a,b,c,e,f,h);this["combinator:!~"](a,b,c,e,f,h)},"!":function(a,b,c,e,f,h){for(;a=a.parentNode;)a!==
document&&this.push(a,b,c,e,f,h)},"!>":function(a,b,c,e,f,h){a=a.parentNode;a!==document&&this.push(a,b,c,e,f,h)},"!+":function(a,b,c,e,f,h){for(;a=a.previousSibling;)if(1===a.nodeType){this.push(a,b,c,e,f,h);break}},"!^":function(a,b,c,e,f,h){if(a=a.lastChild)if(1===a.nodeType)this.push(a,b,c,e,f,h);else this["combinator:!+"](a,b,c,e,f,h)},"!~":function(a,b,c,e,f,h){for(;a=a.previousSibling;)if(1===a.nodeType){var g=this.getUID(a);if(this.bitUniques[g])break;this.bitUniques[g]=!0;this.push(a,b,c,
e,f,h)}}},f;for(f in i)c["combinator:"+f]=i[f];var i={empty:function(a){var b=a.firstChild;return!(b&&1==b.nodeType)&&!(a.innerText||a.textContent||"").length},not:function(a,b){return!this.matchNode(a,b)},contains:function(a,b){return-1<(a.innerText||a.textContent||"").indexOf(b)},"first-child":function(a){for(;a=a.previousSibling;)if(1===a.nodeType)return!1;return!0},"last-child":function(a){for(;a=a.nextSibling;)if(1===a.nodeType)return!1;return!0},"only-child":function(a){for(var b=a;b=b.previousSibling;)if(1===
b.nodeType)return!1;for(;a=a.nextSibling;)if(1===a.nodeType)return!1;return!0},"nth-child":c.createNTHPseudo("firstChild","nextSibling","posNTH"),"nth-last-child":c.createNTHPseudo("lastChild","previousSibling","posNTHLast"),"nth-of-type":c.createNTHPseudo("firstChild","nextSibling","posNTHType",!0),"nth-last-of-type":c.createNTHPseudo("lastChild","previousSibling","posNTHTypeLast",!0),index:function(a,b){return this["pseudo:nth-child"](a,""+b+1)},even:function(a){return this["pseudo:nth-child"](a,
"2n")},odd:function(a){return this["pseudo:nth-child"](a,"2n+1")},"first-of-type":function(a){for(var b=a.nodeName;a=a.previousSibling;)if(a.nodeName===b)return!1;return!0},"last-of-type":function(a){for(var b=a.nodeName;a=a.nextSibling;)if(a.nodeName===b)return!1;return!0},"only-of-type":function(a){for(var b=a,c=a.nodeName;b=b.previousSibling;)if(b.nodeName===c)return!1;for(;a=a.nextSibling;)if(a.nodeName===c)return!1;return!0},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===
a.disabled},checked:function(a){return a.checked},selected:function(a){return a.selected},focus:function(a){return!this.isXMLDocument&&this.document.activeElement===a&&(a.href||a.type||this.hasAttribute(a,"tabindex"))}},k;for(k in i)c["pseudo:"+k]=i[k];c.attributeGetters={"class":function(){return"className"in this?this.className:this.getAttribute("class")},"for":function(){return"htmlFor"in this?this.htmlFor:this.getAttribute("for")},href:function(){return"href"in this?this.getAttribute("href",2):
this.getAttribute("href")},style:function(){return this.style?this.style.cssText:this.getAttribute("style")}};c.getAttribute=function(a,b){var c=this.attributeGetters[b];return c?c.call(a):(c=a.getAttributeNode(b))?c.nodeValue:null};c.overrides=[];c.override=function(a,b){this.overrides.push({regexp:a,method:b})};c.override(/./,function(a,b,d){if(!this.querySelectorAll||9!=this.nodeType||c.isXMLDocument||c.brokenMixedCaseQSA||g.disableQSA)return!1;var e;try{if(d)return this.querySelector(a)||null;
e=this.querySelectorAll(a)}catch(f){return!1}var h=!!b.length;if(c.starSelectsClosedQSA)for(d=0;a=e[d++];)"@"<a.nodeName&&(!h||!c.uniques[c.getUIDHTML(a)])&&b.push(a);else for(d=0;a=e[d++];)(!h||!c.uniques[c.getUIDHTML(a)])&&b.push(a);h&&c.sort(b);return!0});c.override(/^[\w-]+$|^\*$/,function(a,b,d){if("*"==a&&c.brokenStarGEBTN)return!1;a=this.getElementsByTagName(a);if(d)return a[0]||null;for(var e,f=!!b.length,d=0;e=a[d++];)(!f||!c.uniques[c.getUID(e)])&&b.push(e);f&&c.sort(b);return!0});c.override(/^\.[\w-]+$/,
function(a,b,d){if(c.isXMLDocument||!this.getElementsByClassName&&this.querySelectorAll)return!1;var e,f,h=!(!b||!b.length),j=a.substring(1);if(this.getElementsByClassName&&!c.brokenGEBCN){a=this.getElementsByClassName(j);if(d)return a[0]||null;for(f=0;e=a[f++];)(!h||!c.uniques[c.getUIDHTML(e)])&&b.push(e)}else{var i=RegExp("(^|\\s)"+g.escapeRegExp(j)+"(\\s|$)"),a=this.getElementsByTagName("*");for(f=0;e=a[f++];)if((j=e.className)&&i.test(j)){if(d)return e;(!h||!c.uniques[c.getUIDHTML(e)])&&b.push(e)}}h&&
c.sort(b);return d?null:!0});c.override(/^#[\w-]+$/,function(a,b,d){if(c.isXMLDocument||9!=this.nodeType)return!1;var e=a.substring(1),a=this.getElementById(e);if(!a)return b;if(c.idGetsName&&a.getAttributeNode("id").nodeValue!=e)return!1;if(d)return a||null;d=!!b.length;(!d||!c.uniques[c.getUIDHTML(a)])&&b.push(a);d&&c.sort(b);return!0});"undefined"!=typeof document&&c.setDocument(document);var g=c.Slick=this.Slick||{};g.version="0.9dev";g.search=function(a,b,d){return c.search(a,b,d)};g.find=function(a,
b){return c.search(a,b,null,!0)};g.contains=function(a,b){c.setDocument(a);return c.contains(a,b)};g.getAttribute=function(a,b){return c.getAttribute(a,b)};g.match=function(a,b){if(!a||!b)return!1;if(!b||b===a)return!0;if("string"!=typeof b)return!1;c.setDocument(a);return c.matchNode(a,b)};g.defineAttributeGetter=function(a,b){c.attributeGetters[a]=b;return this};g.lookupAttributeGetter=function(a){return c.attributeGetters[a]};g.definePseudo=function(a,b){c["pseudo:"+a]=function(a,c){return b.call(a,
c)};return this};g.lookupPseudo=function(a){var b=c["pseudo:"+a];return b?function(a){return b.call(this,a)}:null};g.override=function(a,b){c.override(a,b);return this};g.isXML=c.isXML;g.uidOf=function(a){return c.getUIDHTML(a)};this.Slick||(this.Slick=g)}).apply("undefined"!=typeof exports?exports:this);
(function(){function c(a,b,c,e,j,l,o,r,t,w,p,x,B,C){if(b||-1===f)if(i.expressions[++f]=[],k=-1,b)return"";if(c||e||-1===k)c=c||" ",a=i.expressions[f],g&&a[k]&&(a[k].reverseCombinator=m(c)),a[++k]={combinator:c,tag:"*"};c=i.expressions[f][k];if(j)c.tag=j.replace(d,"");else if(l)c.id=l.replace(d,"");else if(o)o=o.replace(d,""),c.classList||(c.classList=[]),c.classes||(c.classes=[]),c.classList.push(o),c.classes.push({value:o,regexp:RegExp("(^|\\s)"+h(o)+"(\\s|$)")});else if(x)C=C?C.replace(d,""):null,
c.pseudos||(c.pseudos=[]),c.pseudos.push({key:x.replace(d,""),value:C});else if(r){var r=r.replace(d,""),p=(p||"").replace(d,""),y,v;switch(t){case "^=":v=RegExp("^"+h(p));break;case "$=":v=RegExp(h(p)+"$");break;case "~=":v=RegExp("(^|\\s)"+h(p)+"(\\s|$)");break;case "|=":v=RegExp("^"+h(p)+"(-|$)");break;case "=":y=function(a){return p==a};break;case "*=":y=function(a){return a&&-1<a.indexOf(p)};break;case "!=":y=function(a){return p!=a};break;default:y=function(a){return!!a}}y||(y=function(a){return a&&
v.test(a)});c.attributes||(c.attributes=[]);c.attributes.push({key:r,operator:t,value:p,test:y})}return""}var i,f,k,g,a={},b={},d=/\\/g,e=function(d,h){if(!d)return null;if(!0===d.Slick)return d;var d=(""+d).replace(/^\s+|\s+$/g,""),n=(g=!!h)?b:a;if(n[d])return n[d];i={Slick:!0,expressions:[],raw:d,reverse:function(){return e(this.raw,!0)}};for(f=-1;d!=(d=d.replace(j,c)););i.length=i.expressions.length;var u=d,k;if(g){k=i;for(var l=k.expressions,o=0;o<l.length;o++){for(var r=l[o],t={parts:[],tag:"*",
combinator:m(r[0].combinator)},w=0;w<r.length;w++){var p=r[w];p.reverseCombinator||(p.reverseCombinator=" ");p.combinator=p.reverseCombinator;delete p.reverseCombinator}r.reverse().push(t)}}else k=i;return n[u]=k},m=function(a){return"!"===a?" ":" "===a?"!":/^!/.test(a)?a.replace(/^!/,""):"!"+a},h=function(a){return a.replace(/[-[\]{}()*+?.\\^$|,#\s]/g,"\\$&")},j=RegExp("^(?:\\s*(,)\\s*|\\s*(<combinator>+)\\s*|(\\s+)|(<unicode>+|\\*)|\\#(<unicode>+)|\\.(<unicode>+)|\\[\\s*(<unicode1>+)(?:\\s*([*^$!~|]?=)(?:\\s*(?:([\"']?)(.*?)\\9)))?\\s*\\](?!\\])|:+(<unicode>+)(?:\\((?:([\"']?)((?:\\([^\\)]+\\)|[^\\(\\)]*)+)\\12)\\))?)".replace(/<combinator>/,
"["+h(">+~`!@$%^&={}\\;</")+"]").replace(/<unicode>/g,"(?:[\\w\\u00a1-\\uFFFF-]|\\\\[^\\s0-9a-f])").replace(/<unicode1>/g,"(?:[:\\w\\u00a1-\\uFFFF-]|\\\\[^\\s0-9a-f])")),l=this.Slick||{};l.parse=function(a){return e(a)};l.escapeRegExp=h;this.Slick||(this.Slick=l)}).apply("undefined"!=typeof exports?exports:this);
(function(c){var i=Slick;c.__SELECTOR={find:function(f,k,g){var k=c.makeArray(k||document),a=[],b=k.length,d=0,e;if(f)for(;d<b;d++)if(e=k[d],g){if(e=i.find(e,f)){a[0]=e;break}}else e=i.search(e,f),e.length&&(a=a.concat(e));return a},contains:i.contains,match:i.match,parse:i.parse,uid:i.uidOf}})(DP);
(function(c){function i(a){var b={},c=a[1]>>>0,h=a[2]>>>0;b.major=a[0]>>>0;b.minor=c;b.revision=h;return b}var f=c.UA={},k=/[A-Za-z\s]+/g,g={webkit:/webkit[ \/]([^ ]+)/,opera:/opera(?:.*version)?[ \/]([\w.]+)/,ie:/msie ([\w.]+)/,mozilla:/mozilla(?:.*? rv:([\w.]+))?/},a=null,b=navigator.userAgent.toLowerCase(),c=navigator.platform.toLowerCase();["webkit","opera","ie","mozilla"].forEach(function(a){if(!f.version){var c=b.match(g[a]);c&&(f[a]=f.version=parseInt(c[1]),f.fullVersion=c[1])}});f.platform=
c=c.match(/ip(?:ad|od|hone)/)?"ios":(c.match(/(?:webos|android)/)||c.match(/mac|win|linux/)||["other"])[0];"other"!==c&&(f[c]=!0);f.getFlashVersion=function(){var b;if(!(b=a)){var c,g,h;if(f.ie){try{g=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),c=g.GetVariable("$version")}catch(j){}if(!c)try{g=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),c="WIN 6,0,21,0",g.AllowScriptAccess="always",c=g.GetVariable("$version")}catch(l){h=null}c&&(h=i(c.replace(/[A-Za-z\s]+/g,"").split(",")))}else if(b=
navigator.mimeTypes["application/x-shockwave-flash"])if(b=b.enabledPlugin)c=b.description.replace(/\s[rd]/g,".").replace(k,"").split("."),h=i(c);b=a=h}return b}})(DP);
(function(c){function i(a){var b;return c.isWindow(a)||a&&(b=a.nodeType)&&(1===b||9===b)}function f(a,b){if(a instanceof f)return a;if(this instanceof f)this.context=c.makeArray(a).filter(i);else return m(a,b)}function k(a,b,d){var g=f.prototype;if(c.isPlainObject(a)){var d=e[b]||e.def,i;for(i in a)d(g,i,a[i])}else d=e[d]||e.def,d(g,a,b);return f}var g=c.__HOST,a=g.$,b=c.__SELECTOR,d=c.__,e={iterator:function(a,b,c){a[b]=function(){for(var a=this.context,b=0,e=a.length;b<e;b++)c.apply(a[b],arguments);
return this}},def:function(a,b,c){a[b]=c}},m=function(a,e){var g;g=c.isString(a)?b.find(a,!e||i(e)?e:e._===d&&e.context,!0):a;return new f(g)};f.all=function(a,e){return c.isString(a)?new f(b.find(a,!e||i(e)?e:e._===d&&e.context)):m(a)};f.prototype._=d;k({one:function(a){return new f(b.find(a,this.context,!0))},all:function(a){return new f(b.find(a,this.context))},el:function(a){var b=this.context;return c.isNumber(a)?b[a]:c.clone(b)},get:function(a){return new f(this.context[a])},count:function(){return this.context.length},
forEach:function(a){this.context.forEach(a);return this}});g.$=c.DOM=f;f.methods={};f.__storage={};f.extend=k;f.SELECTOR=b;f.noConflict=function(){g.$=a;return f}})(DP,null);
DP.DOM.feature=function(){var c=document,i=c.defaultView,f=c.createElement("div"),k,g,a,b;f.innerHTML=' <link/><table></table><a href="/a" style="top:1px;float:left;opacity:.7;">a</a><input type="checkbox"/>';b=f.getElementsByTagName("a")[0];try{k=c.createElement("<input name=x>"),g="x"==k.name,a=function(a){return(""+a).replace(/&/g,"&amp;").replace(/"/g,"&quot;")}}catch(d){}return{computedStyle:!(!i||!i.getComputedStyle),opacity:/^0.7$/.test(b.style.opacity),compactEl:!c.compatMode||"CSS1Compat"===
c.compatMode?function(a){return a.documentElement}:function(a){return a.body},addEvent:f.addEventListener?function(a,b,c,d){a.addEventListener(b,c,!!d)}:function(a,b,c){a.attachEvent("on"+b,c)},removeEvent:f.removeEventListener?function(a,b,c,d){a.removeEventListener(b,c,!!d)}:function(a,b,c){a.detachEvent("on"+b,c)},fragment:g?function(b,c){var d=c.name,f=c.type,b="<"+b;d&&(b+=' name="'+a(d)+'"');f&&(b+=' type="'+a(f)+'"');b+=">";delete c.name;delete c.type;return b}:function(a){return a}}}();
(function(c){function i(a){a=d.uid(a);return m[a]||(m[a]={})}function f(a){a=a.relatedTarget;try{if(!a||a===document||a.parentNode){for(;a&&a!==this;)a=a.parentNode;if(a!==this)return!0}}catch(b){}}function k(a,b,c,e){l(a,b.base,b.vals[c],e);delete b.fns[c];delete b.vals[c]}function g(b,e,d){if(b instanceof g)return b;if(b){e||(e=c.__HOST);b||(b=e.event);d||(d={});var f=this.type=d.type||b.type,j=this.base=d.base||f,i=this.target=b.target||b.srcElement,d=this.page={},f=this.client={};this.event=b;
for(c.mix(this,b,!0,["shiftKey","ctrlKey","altKey","metaKey"]);i&&3==i.nodeType;)i=i.parentNode;if(-1!==j.indexOf("key"))this.code=b.which||b.keyCode;else if("click"===j||"dblclick"===j||"contextmenu"===j||/mouse/i.test(j)||j===a){if(i=h(e.document),d.x=null!=b.pageX?b.pageX:b.clientX+i.scrollLeft,d.y=null!=b.pageY?b.pageY:b.clientY+i.scrollTop,f.x=null!=b.pageX?b.pageX-e.pageXOffset:b.clientX,f.y=null!=b.pageY?b.pageY-e.pageYOffset:b.clientY,j===a&&(this.wheel=b.wheelDelta?b.wheelDelta/120:-(b.detail||
0)/3),this.rightClick=3==b.which||2==b.button,"mouseover"==j||"mouseout"==j){for(b=b.relatedTarget||b[("mouseover"==j?"from":"to")+"Element"];b&&3==b.nodeType;)b=b.parentNode;this.relatedTarget=b}}else if(/^(?:gesture|touch)/i.test(j)&&(c.mix(this,b,!0,["rotation","scale","targetTouches","changedTouches","touches"]),b=this.touches&&this.touches[0]))d.x=b.pageX,d.y=b.pageY,f.x=b.clientX,f.y=b.clientY}}g.prototype={stop:function(){return this.stopBubble().prevent()},stopBubble:function(){var a=this.event;
a&&(a.stopPropagation?a.stopPropagation():a.cancelBubble=!0);return this},prevent:function(){var a=this.event;a&&(a.preventDefault?a.preventDefault():a.returnValue=!1);return this}};var a=c.UA.mozilla&&!document.documentMode?"DOMMouseScroll":"onwheel"in document?"wheel":"onmousewheel"in document?"mousewheel":"DOMMouseScroll",b=c.DOM,d=b.SELECTOR,e=b.feature,m=b.__storage.events={},h=e.compactEl,j=e.addEvent,l=e.removeEvent,q={mouseenter:{base:"mouseover",condition:f},mouseleave:{base:"mouseout",condition:f},
mousewheel:{base:a}},s={unload:!0,beforeunload:!0,resize:!0,move:!0,DOMContentLoaded:!0,readystatechange:!0,error:!0,abort:!0,scroll:!0};m._clean=function(a){(a=m[a])&&c.each(a,function(a,b){a.fns.length=a.vals.length=0;delete this[b]})};b.extend({on:c._overloadSetter(function(a,b,c){var e=this,d=i(e),f=d[a],h;f||(h=q[a],f=d[a]={fns:[],vals:[]},f.base=h&&h.base||a,f.c=h&&h.condition,f.n=s[m]);d=f.fns;if(-1===d.indexOf(b)){d.push(b);var k,m=f.base;k=f.c?function(a){return f.c.call(this,a)?b.call(this,
a):true}:b;d=f.n?function(){return k.call(e)}:function(b){b=new g(b,"setInterval"in e?e:"getElementById"in e?e.window:e.ownerDocument.window,{type:a,base:m});k.call(e,b)===false&&b.stop()};f.vals.push(d);j(e,m,d,c)}}),off:c._overloadSetter(function(a,b,c){var e=this,d=i(e),f;if(d)if(b)d=(f=d[a])?f.fns.indexOf(b):-1,-1!==d&&k(e,f,d,c);else for(var a=a?d[a]?[a]:[]:Object.keys(d),b=a.length,h;b--;)h=a[b],f=d[h],f.fns.forEach(function(a,b){a&&k(e,f,b,c)}),f.fns.length=f.vals.length=0,delete d[h]},!0),
fire:function(a){var b=i(this);b[a]&&b[a].vals.forEach(function(a){a()})}},"iterator");b.Event=g;b.Events=q})(DP);
(function(c){function i(a){return a.replace(b,function(a,b){return b.toUpperCase()})}function f(b){var b=i("float"===b?l:b),c;if((c=q[b])&&c.GET)c=c.GET(this);else if(c=this.style[b],!c||"zIndex"===b)c=a(this,b);return c}function k(a,b){var c="width"===b?["left","right"]:["top","bottom"],e=a[i("offset-"+b)];c.forEach(function(a){e-=(parseFloat(f.call(this,"border-"+a+"-width"))||0)+(parseFloat(f.call(this,"padding-"+a))||0)},a);return e}var g=c.DOM,a,b=/-([a-z])/ig,d=/[A-Z]/g,e=/opacity=([^)]*)/,
m=/alpha\([^)]*\)/i,h={position:"absolute",visibility:"hidden",display:"block"},j=g.feature,l="cssFloat"in document.documentElement.style?"cssFloat":"styleFloat",q={},s={width:!0,height:!0,maxwidth:!0,maxheight:!0,minwidth:!0,minheight:!0,textindent:!0,fontsize:!0,letterspacing:!0,lineheight:!0,margin:!0,padding:!0,borderwidth:!0};a=j.curCSS=j.computedStyle?function(a,b){var c=("setInterval"in a?a.document:"getElementById"in a?a:a.ownerDocument).defaultView;return(c=c?c.getComputedStyle(a,null):null)?
c.getPropertyValue(b===l?"float":b.replace(d,function(a){return"-"+a})):null}:function(a,b){var c=a.currentStyle;return c&&c[i(b)]||""};j.opacity||(q.opacity={SET:function(a,b){var c=a.style,e=a.currentStyle,e=e&&e.filter||c.filter||"";c.zoom=1;b=(b=Number(b))||0===b?"alpha(opacity="+100*b+")":"";c.filter=m.test(e)?e.replace(m,b):e+" "+b},GET:function(b){return""+(e.test(a(b,"filter")||"")?parseFloat(RegExp.$1)/100:1)}});["height","width"].forEach(function(a){q[a]={GET:function(b){var c;if(b.offsetWidth===
0){var e={},d;for(d in h){e[d]=b.style[d];b.style[d]=h[d]}(function(){c=k(b,a)}).call(b);for(d in h)b.style[d]=e[d]}else c=k(b,a);return c}}});["top","right","bottom","left"].forEach(function(a){s[a]=s["margin"+a]=s["padding"+a]=s["border"+a+"width"]=true});g.methods.css={len:1,SET:c._overloadSetter(function(a,b){var a=i(a==="float"?l:a),c=q[a];if(c&&c.SET)c.SET(this,b);else{if(s[a.toLowerCase()]&&(b=b+"")&&b===""+Number(b))b=(Number(b)||0)+"px";this.style[a]=b}}),GET:f}})(DP,null);
(function(c){function i(a,b){if(!a)return b;for(var a=k.parse(a),c=a.expressions,e=c.length;e--;)c[e][0].combinator=b;return a}var f=c.DOM,k=c.__SELECTOR,g={prev:{op:"!~",f:!0},prevAll:{op:"!~"},next:{op:"~",f:!0},nextAll:{op:"~"},child:{op:">",f:!0},children:{op:">"},parent:{op:"!",f:!0},parents:{op:"!"}};c.each(g,function(a,b){this[b]=function(b){return new f(k.find(i(b,a.op),this.context.slice(0,1),a.f))}});f.extend(g).extend({first:function(){return new f(this.context.slice(0,1))},last:function(){return new f(this.context.slice(-1))}})})(DP);
(function(c,i,f){function k(a,b){var c=z;return-1!==(c+a.className+c).indexOf(c+b+c)}function g(a){k(this,a)||(this.className=(this.className+z+a).trim())}function a(a){this.className=this.className.replace(RegExp("(?:^|\\s+)"+a+"(?:\\s+|$)")," ").trim()}function b(a){a=n.uid(a);return r[a]||(r[a]={})}function d(a){var b=n.uid(a);(new s(a)).off();a.clearAttributes&&a.clearAttributes();c.each(u,function(a){a._clean?a._clean(b):delete a[b]})}function e(a,b){return function(){var e=this.context,d=arguments,
f=d[0],h=d.length,g,j=0===b;if(b===h&&(j||c.isString(f)))return e[0]?a.GET.call(e[0],f):null;if(h>=b&&(j||f))(g=a.SET)&&e.forEach(function(a){g.apply(a,d)});return this}}function m(){var a=this.parentNode;a&&a.removeChild(this)}function h(){A(this.childNodes).forEach(function(a){m.call(a)})}function j(a,b,c){b=b instanceof s?b.context:A(b).filter(function(a){return a&&a.nodeType});"top"===c&&(b=b.reverse());b.forEach(function(b){b&&C[c||"bottom"](b,a)})}function l(a){var b=a.getAttributeNode("value");
return!b||b.specified?a.value:a.text}function q(a){return null==a?"":a+""}var s=c.DOM,n=s.SELECTOR,u=s.__storage={},A=c.makeArray,z=" ",o=s.methods,r=u.data={},t={tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},w;w="textContent"in document.createElement("div")?"textContent":"innerText";
var p={"for":!0,"class":!0,type:!0},x=/^(?:href|src|usemap)$/i,B="compact nowrap ismap declare noshade checked disabled readOnly multiple selected noresize defer defaultChecked".split(" "),C={before:function(a,b){var c=b.parentNode;c&&c.insertBefore(a,b)},after:function(a,b){var c=b.parentNode;c&&c.insertBefore(a,b.nextSibling)},bottom:function(a,b){b.appendChild(a)},top:function(a,b){b.insertBefore(a,b.firstChild)}},y={option:{GET:l},select:{GET:function(a){return(a=a.options[a.selectedIndex])?l(a):
""},SET:function(a,b){var c=A(b);A(a.options,[],!0).forEach(function(a){a.selected=-1!==c.indexOf(l(a))});c.length||(a.selectedIndex=-1)}}};o.attr={len:1,SET:c._overloadSetter(function(a,b){var c=t[a]||a;a in p?this[c]=b:-1!==B.indexOf(c)?this[c]=!!b:this.setAttribute(c,""+b)}),GET:function(a){var b=t[a]||a,c;return a in p?this[b]:x.test(b)?this.getAttribute(b,2):-1!==B.indexOf(b)?!!this[b]:(c=this.getAttributeNode(b))?c.nodeValue:i}};o.data={len:1,SET:c._overloadSetter(function(a,c){b(this)[a]=c}),
GET:function(a){return b(this)[a]}};var v=!1,E=document.createElement("table"),F=document.createElement("div"),D;try{E.innerHTML="<tr><td></td></tr>",v=!0}catch(G){}E=i;v||(D={table:[1,"<table>","</table>"],select:[1,"<select>","</select>"],tbody:[2,"<table><tbody>","</tbody></table>"],tr:[3,"<table><tbody><tr>","</tr></tbody></table>"]},D.thead=D.tfoot=D.tbody);o.html={SET:function(a){var b=!v&&D[this.tagName.toLowerCase()];if(b){var c=F,e=b[0];for(c.innerHTML=b[1]+a+b[2];e--;)c=c.firstChild;h.call(this);
j(this,c.childNodes)}else this.innerHTML=a},GET:function(){return this.innerHTML}};o.text={SET:function(a){h.call(this);this[w]=a},GET:function(){return this[w]}};o.val={SET:function(a){if(this.nodeType===1){var b=this.nodeName.toLowerCase();(b=y[b])&&(b=b.SET);a=c.isArray(a)?a.map(q):q(a);b?b(this,a):this.value=a}},GET:function(){var a=this.nodeName.toLowerCase();(a=y[a])&&(a=a.GET);return a?a(this):this.value}};s.extend({addClass:g,removeClass:a,toggleClass:function(b){k(this,b)?a.call(this,b):
g.call(this,b)},removeData:function(a){if(a===f)(a=n.uid(this))&&delete r[a];else delete b(this)[a]},removeAttr:function(a){var b=t[a];a in p?this[b]="":B.indexOf(b)!==-1?this[b]=false:self.removeAttribute(b)},inject:function(a,b){var c=a;typeof c==="string"&&(c=s(c));(a=(c=c instanceof s?c.el(0):c)&&c.nodeType?c:false)&&C[b||"bottom"](this,a)},grab:function(a,b){j(this,a,b)},dispose:m,empty:h},"iterator").extend({hasClass:function(a){return k(this.context[0],a)},match:function(a){return n.match(this.context[0],
a)},destroy:function(){this.context.forEach(function(a){var b=c.makeArray(a.getElementsByTagName("*"));b.push(a);b.forEach(d);m.call(a)});return i}});c.each(o,function(a,b){this[b]=e(a,a.len||0);delete a.len});s.extend(o);s._overload=e})(DP,null);(function(c){var i=c.DOM,f=document,k=i.feature.fragment;i.create=function(c,a){a?null!=a.checked&&(a.defaultChecked=a.checked):a={};c=k(c,a);return(new i(f.createElement(c))).attr(a)}})(DP);
(function(c){function i(){var d=a,e;if(d){for(var f=0,h=d.length;f<h;f++)(e=d[f])&&e.call(b,c);d.length=0;a=null}}var f=!1,k=!1,g=c.DOM,a=[],b=c.__HOST;c.isDomReady=function(){return f};c.isLoaded=function(){return!1};c.ready=function(c){if(!k){var e=function(){try{j("left"),m()}catch(a){setTimeout(e,10)}},m=function(){q.off(l,m);s.off("load",m);q=s=null;f||(f=!0,i())},h=b.document,j=h.documentElement.doScroll,l=j?"readystatechange":"DOMContentLoaded",q=new g(h),s=new g(b);k=!0;if("complete"===h.readyState)f||
(f=!0,i());else if(q.on(l,m),s.on("load",m),j){h=!1;try{h=null==win.frameElement}catch(n){}h&&e()}}f?c.call(b,this):a.push(c)}})(DP);
(function(c,i){var f=c.__HOST.document;if(f){var k=f.getElementsByTagName("head")[0],g=/\.(\w+)$/i,a=function(b,c,d){return(d=d||b.match(g)[1])?(a[d.toLowerCase()]||a.img)(b,c):i};a.css=function(a,c){var d=f.createElement("link");d.href=a;d.rel="stylesheet";c&&b.css(d,c);k.appendChild(d);return d};a.js=function(c,d){var h=f.createElement("script");h.src=c;h.async=!0;d&&b.js(h,d);a.__pending=c;k.insertBefore(h,k.firstChild);a.__pending=i;return h};a.img=function(a,b){function c(a){d.onload=d.onabort=
d.onerror=c=i;setTimeout(function(){b.call(d,{type:a});d=i},0)}var d=f.createElement("img");b&&["load","abort","error"].forEach(function(a){d["on"+a]=function(){c(a)}});d.src=a;b&&d.complete&&c&&c("load");return d};var b={js:f.createElement("script").readyState?function(a,b){a.onreadystatechange=function(){var c=a.readyState;if("loaded"===c||"complete"===c)a.onreadystatechange=i,b.call(this)}}:function(a,b){a.addEventListener("load",b,!1)}},d=f.createElement("css").attachEvent?function(a,b){a.attachEvent("onload",
b)}:function(a,b){var f=!1,g=a.sheet;if(g)if(c.UA.webkit)f=!0;else try{g.cssRules&&(f=!0)}catch(i){"NS_ERROR_DOM_SECURITY_ERR"===i.name&&(f=!0)}f?setTimeout(function(){b.call(a)},0):setTimeout(function(){d(a,b)},10)};b.css=d;c.load=a}})(DP,null);
(function(c,i,f){function k(a,b,d){c.isString(a)||(d=b,b=a,a=f);c.isArray(b)||(b&&(d=b),b=f);a&&(a=(a=h(a,f,"/"))&&0===a.indexOf("/")?a:o.applyPath(a));g(a,b,d)}function g(b,c,d){var f={},g;if(b)if(g=q[b])f=g;else{g=b;var h=f;q[g]=h;h.i=g;h.p=[]}else(u&&(g=j()||{},g=g.src||y.__pending),g)?(b=o.santitize(C(g).pathname),f=q[b]):n=f;"function"===typeof d?(f.f=d,f.deps=c,f.ol=function(){var b=this;delete b.ol;b.deps&&b.deps.length?a(b.deps,function(){e(b)},b,!0):e(b)}):Object(d)===d&&(f.exports=d,f.ol=
function(){delete this.ol;m(this)});b&&f.ol&&f.ol();return f}function a(a,e,f,g){var h=a.length,j=[c],k=0,m;c.isFunction(e)&&(m=g?e:function(){e.apply(i,j)});0===h?m&&m():l(a,function(a){var e=b(a,f),l=e.isCSS?0:++k,v=function(){m&&(--h,!g&&l&&(j[l]=d(f)(a)),0===h&&m())};if(e.exports)v();else{e.p.push(v);var p=function(){var a;if(e.isCSS)e.exports=!0;else if(!u&&(a=n))n=i,c.mix(e,a),e.ol&&e.ol()},v=o.getURI(e.i);if(!s[v]){s[v]=!0;var q=e.isCSS?"css":"js",r;r=y[q](v,"css"===q?p:function(){p.call(r);
if(!c._env.debug){try{if(r.clearAttributes)r.clearAttributes();else for(var a in r)delete r[a]}catch(b){}B.removeChild(r)}r=i})}}})}function b(a,b){var c=b.i,d=a,e,f=a.split(r);f[1]&&(d=f[1],e=f[0].toLowerCase());if(f=0===d.indexOf("~/"))d=d.substr(2);if(f||0===d.indexOf("./")||0===d.indexOf("../"))e=b.ns;d=(c=h(d,c,e&&o.appBase+e+"/"))&&0===c.indexOf("/")?c:o.applyPath(c);c=q[d];if(!c&&(c=g(d),w.test(d)&&(c.isCSS=!0),e))c.ns=e;return c}function d(a){return function(c){return b(c,a).exports}}function e(a){var b=
{},e={exports:b};if(!a.exports){var f=a.f,b=f(c,d(a),b,e);a.exports=b||e.exports;m(a)}}function m(a){a.deps&&(a.deps.length=0,delete a.deps);delete a.f;l(a.p,function(a){a()});a.p.length=0;delete a.p;return a}function h(a,b,c){var d=t.test(a),a=a+(d?"":".js");c||(c=o.libBase);b||(b=c);if(a&&0===a.indexOf("/"))c=a;else if(0===a.indexOf("./")||0===a.indexOf("../")){var c=b.match(p),c=((c?c[0]:".")+"/"+a).split("/"),e=[];l(c,function(a){".."===a?(0===e.length&&z(530),e.pop()):"."!==a&&e.push(a)});c=
e.join("/")}else c+=a.replace(/^\/+/,"");return c}function j(){if(A&&"interactive"===A.readyState)return A;for(var a=B.getElementsByTagName("script"),b,c=0,d=a.length;c<d;c++)if(b=a[c],"interactive"===b.readyState)return A=b;return i}function l(a,b){for(var c=0,d=a.length;c<d;c++)b.call(a,a[c],c,a)}var q={},s={},n=i,u=c.UA.ie,A=i,z,o={},r="::",t=/\.(?:js|css)$|#|\?/i,w=/\.css(?:$|#|\?)/i,p=/.*(?=\/.*$)/,x=function(){},B=c.__HOST.document.getElementsByTagName("head")[0],C=c.getLocation,y=c.load;k.__mods=
q;k.on=x;k.off=x;c.define=k;c.provide=function(b,d){b=c.makeArray(b);a(b,d,{})};c.__loader=o})(DP,null);
(function(c){var i=/\.min/i,f=/\.[a-z0-9]{32}/i,k=/\.v(?:\d+\.)*\d+/i,g=/\.[a-z0-9]+$/,a=~document.cookie.indexOf("neuron-debug"),b=c.provide,d=[],e=window.__loaderConfig||{},m=e.server,h=e.appServer||m,j=e.libServer||m,l="/"+(e.libBase||"lib/1.0"),q="/"+(e.appBase||"s/j/app"),s={},n={};if(l===q)throw{message:"libBase same as appBase, which is forbidden",toString:function(){return"DP Loader: libBase same as appBase, which is forbidden"}};c.provide=function(){d.push(arguments)};e=c.__loader;e.applyPath=
function(a,b){return(b?l:q)+a};e.santitize=function(a){return a.replace(i,"").replace(f,"").replace(k,"")};e.appBase=q;e.libBase=l;e.getURI=function(b){var c=0===b.indexOf(l)?j:h,d=b;if(!a){var e=s[b];e&&(d=n[e]?n[e]:b.replace(g,function(a){return".min."+e+a}))}return"//"+c.replace(/\{n\}/g,d.length%3+1)+d};var u=window.__loaderCombo||{};e.init=function(a,e){2===arguments.length&&(s=a,n=e);if(u){var f=u,g,h,i=0,j,k={},l={};for(g in f)h=f[g],j="combo_"+i,g=c.getLocation(g),l[j]=g.pathname,h.forEach(function(a){k[a]=
j}),i++;u={urls:k,combos:l};c.mix(s,u.urls);c.mix(n,u.combos)}c.provide=b;d.forEach(function(a){b.apply(null,a)});delete c.__loader}})(DP);(function(c){var i={};c.data=function(f,k){var g=c._type(f),a={},b,d;void 0===f?(d=c.clone(i),b=!0):"string"===g?void 0===k?(d=i[f],b=!0):(a[f]=k,a&&c.mix(i,a)):"object"===g&&f&&c.mix(i,f);return b?d:c};c.require=function(){var f=c.isString;c.makeArray(arguments).forEach(function(i){f(i)&&(i={mod:i});c.provide(i.mod,function(c,a){a.init&&a.init(i.config)})})}})(DP);
delete DP.__SELECTOR;delete DP.__;"use strict";
(function(){function c(a,b){for(var c in b)a[c]=b[c];return a}function i(a,b,c){a=u(a,b,c);(new Image(1,1)).src=q+a}function f(a){x._setPageId(a);return f}function k(){var a,b=g.performance;a=b&&b.timing;var d=y-C,e=+new Date-C,b={r_pagetiming:1,r_ready:d,r_load:e};a&&c(b,{r_conn:a.connectEnd-a.connectStart,r_recev:a.responseEnd-a.responseStart,r_ready:0<a.domInteractive-a.domLoading?a.domInteractive-a.domLoading:d,r_wait:a.responseStart-a.requestStart,r_load:0<a.loadEventStart-a.domLoading?a.loadEventStart-
a.domLoading:e});if((a=w)||(a=g.DP&&DP.data&&DP.data("hippo_perf_version")))b.test=a;x.mv(b);v(g,"load",k)}var g=window,a=g.document,b=a.referrer,d=a.location.href,e=g.screen,m=0,h=0,j=0,l=function(){},q="//hls."+(/51ping/.test(a.domain)?"51ping":"dianping")+".com/hippo.gif?",s=g.JSON&&JSON.stringify||function(a){var b=[],c,d;for(c in a)d=a[c],Object(d)!==d&&b.push('"'+c+'":"'+(""+d).replace(/"/g,'\\"')+'"');return"{"+b.join(",")+"}"},n=Array.prototype;n.forEach||(n.forEach=function(a,b){for(var c=
0,d=this.length;c<d;c++)c in this&&a.call(b,this[c],c,this)});var u,A,z={};if(e&&(n=e.height,A=e.width,n&&A&&(z.__hsr=A+"x"+n),e=e.colorDepth))z.__hsc=e+"bit";u=function(a,e,f){f=f||{};c(f,B);f={__hlt:"www.dianping.com",__ppp:m,__had:s(f),force:+new Date};c(f,z);d&&(f.__hlh=d);b&&(f.__hlr=b);e.push(j+"|"+h);f[a]=e.join("|");var a=encodeURIComponent,g,i=[];for(g in f){e=f[g];Object(e)!==e&&i.push(g+"="+a(e||""))}return i.join("&")};var o={};c(f,{ext:function(a,b){var c;if(Object(a)===a)for(c in a)f.ext(c,
a[c]);else typeof a==="string"&&Object(b)!==b&&(o[a]=b);return f},rxt:function(a){typeof a==="string"?delete o[a]:arguments.length||(o={});return f},pv:function(a,b){x._setCityId(a);x._setShopType(b);x._setPVInitData(o);return f},mv:function(a,b){if(typeof a==="string"&&Object(b)!==b){o[a]=b;x.mv(o)}return f}});document.hippo=f;var r=!0,t=!0,w,p=g._hip;p||(p=g._hip=[]);var x={_setPageId:function(a){m=a>>>0},_setCityId:function(a){j=a>>>0},_setShopType:function(a){h=a>>>0},_setPVInitData:function(a){x._setPVInitData=
l;setTimeout(function(){i("__pv",[],a||o);o={}},0)},_autoPV:function(a){r=a},_autoPageTiming:function(a){t=a},_setPageTimingVer:function(a){w=a},_setReferrer:function(a){b=a},_setHref:function(a){d=a},_setRequestId:function(a){B.reqid=a},_setGuid:function(a){B.serverguid=a},_setCustomConst:function(a,b){B[a]=b},mv:function(a){i("__mv",["",""],a||o);o={}},pv:function(a){i("__pv",[],a||o);o={}}},B={};p.push=function(a){var b;if(a){b=a.shift();(b=x[b])&&b.apply(null,a)}};p.forEach(function(a){p.push(a)});
r&&p.push(["_setPVInitData"]);p.length=0;var C=g.G_rtop,y,n=a.createElement("div"),e=n.addEventListener?function(a,b,c,d){a.addEventListener(b,c,!!d)}:function(a,b,c){a.attachEvent("on"+b,c)},v=n.removeEventListener?function(a,b,c,d){a.removeEventListener(b,c,!!d)}:function(a,b,c){a.detachEvent("on"+b,c)};if(t){if("complete"===a.readyState)y=+new Date;else{var E=a.documentElement.doScroll,F=E?"readystatechange":"DOMContentLoaded",D=function(){v(a,F,D);v(g,"load",D);y=+new Date};e(a,F,D);e(g,"load",
D);if(E){var G=function(){try{E("left");D()}catch(a){setTimeout(G,10)}},n=!1;try{n=null==g.frameElement}catch(H){}n&&G()}}e(g,"load",k)}"undefined"!==typeof module&&module.exports&&(module.exports=p)})();
